site:
  title: Minetest Docs
  start_page: index.adoc 
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: doc
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
